/**
 * MMS.Print - builds a clean, print-only "statement" layout and hands
 * off to the browser's native print dialog (Save as PDF). No external
 * PDF library needed: the browser handles pagination and font
 * rendering (so ₹ and any user text render correctly), and CSS in
 * style.css hides everything except #print-area while printing.
 */
MMS.Print = (function () {
  "use strict";

  function ensureArea() {
    let area = document.getElementById("print-area");
    if (!area) {
      area = document.createElement("div");
      area.id = "print-area";
      area.className = "print-only";
      document.body.appendChild(area);
    }
    return area;
  }

  function cell(value, align) {
    const td = document.createElement("td");
    if (align === "right") td.className = "num";
    td.textContent = value;
    return td;
  }

  function buildTable(section) {
    const table = document.createElement("table");
    table.className = "print-table";

    const thead = document.createElement("thead");
    const headRow = document.createElement("tr");
    section.columns.forEach((col) => {
      const th = document.createElement("th");
      if (col.align === "right") th.className = "num";
      th.textContent = col.label;
      headRow.appendChild(th);
    });
    thead.appendChild(headRow);
    table.appendChild(thead);

    const tbody = document.createElement("tbody");
    if (section.rows.length === 0) {
      const tr = document.createElement("tr");
      const td = document.createElement("td");
      td.className = "print-empty";
      td.colSpan = section.columns.length;
      td.textContent = "No data";
      tr.appendChild(td);
      tbody.appendChild(tr);
    }
    section.rows.forEach((row) => {
      const tr = document.createElement("tr");
      row.forEach((val, i) => tr.appendChild(cell(val, section.columns[i] && section.columns[i].align)));
      tbody.appendChild(tr);
    });
    if (section.totalRow) {
      const tr = document.createElement("tr");
      tr.className = "print-total-row";
      section.totalRow.forEach((val, i) => tr.appendChild(cell(val, section.columns[i] && section.columns[i].align)));
      tbody.appendChild(tr);
    }
    table.appendChild(tbody);
    return table;
  }

  function build(config) {
    const frag = document.createDocumentFragment();

    const header = document.createElement("div");
    header.className = "print-header";
    const brand = document.createElement("div");
    brand.className = "print-brand";
    brand.textContent = "💰 Money Manager";
    const h1 = document.createElement("h1");
    h1.textContent = config.title;
    header.append(brand, h1);
    (config.meta || []).forEach((m) => {
      const line = document.createElement("div");
      line.className = "print-meta";
      line.textContent = m;
      header.appendChild(line);
    });
    frag.appendChild(header);

    if (config.summary && config.summary.length) {
      const summary = document.createElement("div");
      summary.className = "print-summary";
      config.summary.forEach((s) => {
        const stat = document.createElement("div");
        stat.className = "print-stat";
        const label = document.createElement("div");
        label.className = "print-stat-label";
        label.textContent = s.label;
        const value = document.createElement("div");
        value.className = "print-stat-value";
        value.textContent = s.value;
        stat.append(label, value);
        summary.appendChild(stat);
      });
      frag.appendChild(summary);
    }

    (config.sections || []).forEach((sec) => {
      if (sec.heading) {
        const h2 = document.createElement("h2");
        h2.className = "print-section-title";
        h2.textContent = sec.heading;
        frag.appendChild(h2);
      }
      frag.appendChild(buildTable(sec));
    });

    const footer = document.createElement("div");
    footer.className = "print-footer";
    footer.textContent = `Generated by Money Manager on ${MMS.formatDate(MMS.todayStr())} · Data stored locally on this device`;
    frag.appendChild(footer);

    return frag;
  }

  function show(config) {
    const area = ensureArea();
    area.innerHTML = "";
    area.appendChild(build(config));
    setTimeout(() => window.print(), 60);
  }

  return { show };
})();
